-- SQL Schema for Project Management Application
-- Updated on 2025-07-19

CREATE TABLE ROLES (
    ROLE_ID SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    AGGLO_USER_ID VARCHAR(15) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESIGNATION VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    ROLE_ID INT REFERENCES ROLES(ROLE_ID),
    SUP_USER_ID INT REFERENCES USERS(USER_ID) ON DELETE SET NULL
);

CREATE TABLE CLIENTS (
    CLIENT_ID SERIAL PRIMARY KEY,
    USER_ID INT REFERENCES USERS(USER_ID),
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    ALTER_PHONE_NUMBER VARCHAR(20),
    CLIENT_TYPE VARCHAR(100),
    TIME_ZONE VARCHAR(50),
    AVAILABLE_HRS VARCHAR(100),
    OUR_TIME VARCHAR(100),
    COUNTRY VARCHAR(100),
    ADDRESS TEXT,
    DETAILS TEXT,
    STAKE_HOLDERS TEXT,
    DATE_OF_ENTRY VARCHAR(15),
    INSERT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE QUOTATIONS (
    QUOTATION_ID SERIAL PRIMARY KEY,
    QUOTATION_NUMBER VARCHAR(50),
    DATE_OF_QUOTATION DATE,
    DATE_OF_PROPOSAL DATE,
    PROJECT_NAME VARCHAR(200),
    USER_ID INT REFERENCES USERS(USER_ID),
    CLIENT_ID INT REFERENCES CLIENTS(CLIENT_ID),
    IS_NEW_CLIENT BOOLEAN,
    QUOTATION_VALUE NUMERIC(15,2),
    QUOTATION_STATUS VARCHAR(50),
    COMMENTS TEXT,
    ESTIMATOR_ID INT REFERENCES USERS(USER_ID),
    ASSIGNED_ESTIMATOR_ID INT REFERENCES USERS(USER_ID),
    PROJECT_VALUE NUMERIC(15,2),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CLIENT_PROJECT_NUMBER VARCHAR(100),
    CLIENT_PURCHASE_NUMBER VARCHAR(100),
    CURRENCY VARCHAR(10),
    CONNECTION_ENGINEERING BOOLEAN,
    CONNECTION_ENGINEERING_DESCRIPTION TEXT
);

CREATE TABLE PROJECTS (
    PROJECT_ID SERIAL PRIMARY KEY,
    QUOTATION_ID INT REFERENCES QUOTATIONS(QUOTATION_ID),
    COMMENTS TEXT,
    IFA_DATE DATE,
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROJECT_MANAGER_ID INT REFERENCES USERS(USER_ID),
    PROJECT_STATUS VARCHAR(50),
    PLANNED_SUBMITTED_DATE DATE,
    IFC_SUBMISSION_DATE DATE,
    IFA_SUBMISSION_DATE DATE
);

CREATE TABLE INVOICE (
    INVOICE_ID SERIAL PRIMARY KEY,
    INVOICE_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    INVOICE_DATE DATE,
    DUE_DATE DATE,
    PROJECT_ID INT REFERENCES PROJECTS(PROJECT_ID),
    USER_ID INT REFERENCES USERS(USER_ID),
    BALANCE_AMT NUMERIC(15,2),
    REMARKS TEXT,
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INSERT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PAYMENTS (
    PAYMENT_ID SERIAL PRIMARY KEY,
    INVOICE_ID INT REFERENCES INVOICE(INVOICE_ID),
    AMOUNT_RECEIVED NUMERIC(15,2),
    PAYMENT_DESCRIPTION TEXT,
    PROJECT_ID INT REFERENCES PROJECTS(PROJECT_ID),
    RECEIVED_DATE DATE,
    PAYMENT_MODE VARCHAR(50)
);

CREATE TABLE SALES_TARGETS (
    SALES_TARGETS_ID SERIAL PRIMARY KEY,
    USER_ID INT REFERENCES USERS(USER_ID),
    YEAR NUMERIC(15,2),
    MONTH VARCHAR(10)
);




 ALTER TABLE users
ADD UNIQUE (agglo_user_id);

ALTER TABLE users
ADD COLUMN password VARCHAR(255) NOT NULL;

ALTER TABLE sales_targets
DROP COLUMN month,
ADD COLUMN jan integer,
ADD COLUMN feb integer,
ADD COLUMN mar integer,
ADD COLUMN apr integer,
ADD COLUMN may integer,
ADD COLUMN jun integer,
ADD COLUMN jul integer,
ADD COLUMN aug integer,
ADD COLUMN sep integer,
ADD COLUMN oct integer,
ADD COLUMN nov integer,
ADD COLUMN dec integer;

alter table projects add column client_job_number varchar(30);

alter table projects add column project_number varchar(50);


CREATE TABLE client_convo (
    client_convo_id SERIAL PRIMARY KEY,
    client_id INT NOT NULL,
    user_id INT NOT NULL,
    call_convo TEXT,
    status_update TEXT,
    remarks TEXT,
    FOREIGN KEY (client_id) REFERENCES clients(client_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

 CREATE TABLE work_status (
    work_status_id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    date DATE NOT NULL,
    no_of_calls INT DEFAULT 0,
    samples_send INT DEFAULT 0,
    bids_received INT DEFAULT 0,
    projects_received INT DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

