-- SQL Schema for Project Management Application
-- Generated on 2025-07-05 18:12:48

CREATE TABLE ROLES (
    ROLE_ID SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE USERS (
    EMPLOYEE_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESIGNATION VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    ROLE_ID INT REFERENCES ROLES(ROLE_ID),
    SUB_USER_ID INT REFERENCES USERS(EMPLOYEE_ID) ON DELETE SET NULL
);

CREATE TABLE CLIENTS (
    CLIENT_ID SERIAL PRIMARY KEY,
    EMPLOYEE_ID INT REFERENCES USERS(EMPLOYEE_ID),
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE_NUMBER VARCHAR(20),
    ALTER_PHONE_NUMBER VARCHAR(20),
    TIME_ZONE VARCHAR(50),
    AVAILABLE_HRS VARCHAR(100),
    OUR_TIME VARCHAR(100),
    ADDRESS TEXT,
    DETAILS TEXT,
    INSERT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PROJECTS (
    PROJECT_ID SERIAL PRIMARY KEY,
    PROJECT_NUMBER VARCHAR(50),
    QUOTATION_NUMBER VARCHAR(50),
    DATE_OF_QUOTATION DATE,
    DATE_OF_PROPOSAL DATE,
    PROJECT_NAME VARCHAR(200),
    EMPLOYEE_ID INT REFERENCES USERS(EMPLOYEE_ID),
    CLIENT_ID INT REFERENCES CLIENTS(CLIENT_ID),
    COUNTRY VARCHAR(100),
    QUOTATION_VALUE NUMERIC(15,2),
    QUOTATION_STATUS VARCHAR(50),
    COMMENTS TEXT,
    IFA_DATE DATE,
    ESTIMATOR_ID INT REFERENCES USERS(EMPLOYEE_ID),
    ASSIGNED_ESTIMATOR_ID INT REFERENCES USERS(EMPLOYEE_ID),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CLIENT_PROJECT_NUMBER VARCHAR(100),
    CLIENT_PURCHASE_NUMBER VARCHAR(100),
    CURRENCY VARCHAR(10),
    PROJECT_VALUE NUMERIC(15,2),
    PROJECT_MANAGER_ID INT REFERENCES USERS(EMPLOYEE_ID),
    PROJECT_STATUS VARCHAR(50),
    PLANNED_SUBMITTED_DATE DATE,
    IFC_SUBMISSION_DATE DATE,
    IFA_SUBMISSION_DATE DATE,
    CONNECTION_ENGINEERING BOOLEAN,
    CONNECTION_ENGINEERING_DESCRIPTION TEXT
);

CREATE TABLE INVOICE (
    INVOICE_ID SERIAL PRIMARY KEY,
    INVOICE_NUMBER VARCHAR(50) UNIQUE NOT NULL,
    INVOICE_DATE DATE,
    DUE_DATE DATE,
    PROJECT_ID INT REFERENCES PROJECTS(PROJECT_ID),
    USER_ID INT REFERENCES USERS(EMPLOYEE_ID),
    BALANCE_AMT NUMERIC(15,2),
    REMARKS TEXT,
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INSERT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PAYMENTS (
    PAYMENT_ID SERIAL PRIMARY KEY,
    INVOICE_ID INT REFERENCES INVOICE(INVOICE_ID),
    AMOUNT_RECEIVED NUMERIC(15,2),
    PAYMENT_DESCRIPTION TEXT,
    PROJECT_ID INT REFERENCES PROJECTS(PROJECT_ID),
    RECEIVED_DATE DATE,
    PAYMENT_MODE VARCHAR(50)
);