spring.application.name=insidesales
spring.datasource.url=jdbc:postgresql://localhost:5432/agglotek
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none