spring.application.name=insidesales
spring.datasource.url=jdbc:postgresql://localhost:5432/agglotek
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
# allow 20MB per file
spring.servlet.multipart.max-file-size=20MB
# allow 50MB total request
spring.servlet.multipart.max-request-size=50MB

#Email Parameters for sending mail
mailService.smtp.host=mail.agglotekinc.com
mailService.smtp.port=587
mailService.username=donotreplytest@agglotekinc.com
mailService.password=RK6#ofbJQ8cj

# allow 20MB per file
spring.servlet.multipart.max-file-size=20MB
# allow 50MB total request
spring.servlet.multipart.max-request-size=50MB

